name: S3 Deploy and Cloudfront Cache Clear

on:
  workflow_run:
    workflows: ["Terraform Deploy"]
    types: [completed]
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-2

    - name: Deploy static site to S3 bucket
      if: github.ref == 'refs/heads/"main"' && github.event_name == 'push'
      run: aws s3 sync ./src/ s3://cullancarey.com --delete

    - name: Invalidate Cloudfront Cache
      if: github.ref == 'refs/heads/"main"' && github.event_name == 'push'
      run: aws cloudfront create-invalidation --distribution-id E1EM2WQ96D3J54 --paths '/*'

